---
resources:
  - name: scrum-poker
    type: git
    icon: github-circle
    source:
      uri: https://github.com/KenErasga/scrum-poker.git
      branch: pipeline

jobs:
  - name: test
    public: true
    plan:
      - get: scrum-poker
        trigger: true
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: node, tag: "12" }
          inputs:
            - name: scrum-poker
          run:
            path: /bin/sh
            args: ["scrum-poker/cicd/run_test.sh"]
            # path: scrum-poker/cicd/run_test.sh
            # args:
              # - -c
              # - |
              #   echo "Node Version: $(node --version)"
              #   echo "NPM Version: $(npm --version)"
              #   ls
              #   cd scrum-poker/client
              #   ls
              #   yarn
              #   yarn test

