apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client-container
          image: klae01/client-scrum-poker:1.0.4
          env:
            - name: REACT_APP_COGNITO_REGION
              value: eu-west-2
            - name: REACT_APP_COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: cognitouserpoolid
                  key:  REACT_APP_COGNITO_USER_POOL_ID
            - name: REACT_APP_COGNITO_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cognitoappclientid
                  key: REACT_APP_COGNITO_APP_CLIENT_ID
            - name: REACT_APP_SOCKETIO_HOST
              value: 192.168.99.101:30001
          ports:
            - containerPort: 5000